{"5b43767389f6ac5d3dd76abaf85d56eb":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"c7a76cc50816584","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/c7a76cc50816584","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710214107,"stop":1744710214107,"duration":0}}]},"85b95ccedee2304576b3974c9075ee62":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"7eaad1766b455dda","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/7eaad1766b455dda","status":"passed","time":{"start":1744710204420,"stop":1744710204421,"duration":1}}]},"989cd09db7a61c44ac7478bae84e329b":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"6efc3002411804ec","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/6efc3002411804ec","status":"passed","time":{"start":1744710204384,"stop":1744710204384,"duration":0}}]},"7646af8cb6fbca2caec63f53361b571a":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"1aa0a7bcef7cf42a","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/1aa0a7bcef7cf42a","status":"passed","time":{"start":1744710204439,"stop":1744710204439,"duration":0}}]},"8084881d40b5a67bd5437327acba36f8":{"statistic":{"failed":0,"broken":0,"skipped":1,"passed":0,"unknown":0,"total":1},"items":[{"uid":"baf59e54e3eec7b7","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/baf59e54e3eec7b7","status":"skipped","statusDetails":"Skipped: got empty parameter set ['dag_file'], function test_dag_integrity at /home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/test/test_dags_general.py:219","time":{"start":1744710204447,"stop":1744710204447,"duration":0}}]},"41e6f1dd39988f2434380212d31cfe61":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"6d8e3a875fa74599","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/6d8e3a875fa74599","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710210539,"stop":1744710210539,"duration":0}}]},"406b7b002c032c4bb8640f3e4783d3c5":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e997216971b9c799","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/e997216971b9c799","status":"failed","statusDetails":"AssertionError: DAG not found in DagBag\nassert 'etl_pipeline' in {}\n +  where {} = <airflow.models.dagbag.DagBag object at 0x7f94fb6e9730>.dags","time":{"start":1744710211035,"stop":1744710211036,"duration":1}}]},"8123bfdf5d814420b0449ca1f8e4137a":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4d4b00f7ae0fe5a2","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/4d4b00f7ae0fe5a2","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710213127,"stop":1744710213127,"duration":0}}]},"f6228bd2bd85a09224208e409d0188f3":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"efb3c5a971012c9c","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/efb3c5a971012c9c","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710212112,"stop":1744710212112,"duration":0}}]},"c047b85cd9b47f6a5d7eed1dc89b1bc5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b772ccfcfe8bcecb","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/b772ccfcfe8bcecb","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710206527,"stop":1744710206527,"duration":0}}]},"d61ea86c0f6e16cc409fc200a3e87747":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"760ac172b215392","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/760ac172b215392","status":"passed","time":{"start":1744710204402,"stop":1744710204402,"duration":0}}]},"6d1f11ba488a77b795fec33eafaf921a":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1cfa06e8d66c87e0","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/1cfa06e8d66c87e0","status":"failed","statusDetails":"AssertionError: Expected 3 DAGs, got 2\nassert 2 == 3\n +  where 2 = len({'dbt_docs_generator': <DAG: dbt_docs_generator>, 'etl_pipeline': <DAG: etl_pipeline>})\n +    where {'dbt_docs_generator': <DAG: dbt_docs_generator>, 'etl_pipeline': <DAG: etl_pipeline>} = <airflow.models.dagbag.DagBag object at 0x7f94fb78c880>.dags","time":{"start":1744710204306,"stop":1744710204306,"duration":0}}]},"b23d06ac49a08cbec13bbb237978433c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d140d2760182116","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/d140d2760182116","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710208100,"stop":1744710208100,"duration":0}}]},"51aece03088b09e8960bf62ecc0daa7b":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"dd84328c3478e2ff","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/dd84328c3478e2ff","status":"passed","time":{"start":1744710204424,"stop":1744710204424,"duration":0}}]},"3f5a6b74db626b49f67ff0b3e87bf544":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"504d34b6770133db","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/504d34b6770133db","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710212628,"stop":1744710212628,"duration":0}}]},"03916089dcbe53cf7a184f6bed70249d":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"30ceeb000949edf5","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/30ceeb000949edf5","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710207007,"stop":1744710207007,"duration":0}}]},"08cd95137364441a265e5d688e97b0d2":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"b72e78c83a98431b","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/b72e78c83a98431b","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710209582,"stop":1744710209582,"duration":0}}]},"ee6612053e11e705f03efc669026e621":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"93857e2624d35457","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/93857e2624d35457","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710213614,"stop":1744710213614,"duration":0}}]},"e5465adc47fdb2a65325579951342ca8":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"5f62298ba55a6c9d","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/5f62298ba55a6c9d","status":"passed","time":{"start":1744710204348,"stop":1744710204348,"duration":0}}]},"712cc4addafa2e4153014a9664fb2231":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"a0179e54aeaa2c5c","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/a0179e54aeaa2c5c","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710208604,"stop":1744710208604,"duration":0}}]},"9e3392efea089e97eca8fd614b0aa051":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"771930c94078941a","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/771930c94078941a","status":"passed","time":{"start":1744710204442,"stop":1744710204442,"duration":0}}]},"88a0265732ed66ceda2dd93555a37647":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"76feefdf19b81e51","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/76feefdf19b81e51","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710211042,"stop":1744710211042,"duration":0}}]},"24025e40e135a5446171c640629617d9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3fe5e8267df3a9ce","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/3fe5e8267df3a9ce","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710210065,"stop":1744710210065,"duration":0}}]},"49c9f2efd0992acb24b508916d2959fd":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"5820fea962c5550c","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/5820fea962c5550c","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710209104,"stop":1744710209104,"duration":0}}]},"36067630244a49436daf62526f716d7c":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"cc104c9998bdb046","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/cc104c9998bdb046","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('nexabrands_dbt_incremental_dag',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710207589,"stop":1744710207589,"duration":0}}]},"0f365ff60f191dc6df0fbad309cf102a":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"86772ee8705bd067","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/86772ee8705bd067","status":"passed","time":{"start":1744710204445,"stop":1744710204446,"duration":1}}]},"07ea110e884a72226c41ab30940c80ed":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e1d33708ef0a4220","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/e1d33708ef0a4220","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710204450,"stop":1744710204450,"duration":0}}]},"2b396d3c15ee2024475aeb9fa74d6ea1":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"983156faae7089f5","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/983156faae7089f5","status":"passed","time":{"start":1744710214592,"stop":1744710214595,"duration":3}}]},"f67c242461f1da2871b849f903983483":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"30b19239f3e2a2fc","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/30b19239f3e2a2fc","status":"passed","time":{"start":1744710204436,"stop":1744710204436,"duration":0}}]},"b7f0e57849761f4fb2d92586b3808d1e":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"88e82fe7229fb892","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/88e82fe7229fb892","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('etl_pipeline',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710211612,"stop":1744710211612,"duration":0}}]},"1b819c0c7809385a7f25095d75c773c5":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"23c57c976637ea6","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/23c57c976637ea6","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710205545,"stop":1744710205545,"duration":0}}]},"cfb00551ea92b6eca3f268b0f892c942":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e66471bae89fb3df","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/e66471bae89fb3df","status":"passed","time":{"start":1744710204366,"stop":1744710204366,"duration":0}}]},"166f6681a38c1023b4ff492def40bf75":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2462957154c5055e","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/2462957154c5055e","status":"failed","statusDetails":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7f9504774280>.import_errors","time":{"start":1744710204125,"stop":1744710204126,"duration":1}}]},"e936d9b66761de10c5efd8d1b02f7a56":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"59966bbc8e0fb643","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/59966bbc8e0fb643","status":"broken","statusDetails":"Exception: dags/dbt_simple_task_group.py failed to import with message \n Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\n    project_config.validate_project()\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json","time":{"start":1744710204426,"stop":1744710204427,"duration":1}}]},"0a0ed91205923ec98ce81afed9a74e1b":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f7e6342705e3e24d","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/f7e6342705e3e24d","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710206040,"stop":1744710206040,"duration":0}}]},"a6ded196bff64ea5a9d8a048df3ba1d3":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"cf02c8a02811cd3c","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/cf02c8a02811cd3c","status":"passed","time":{"start":1744710204329,"stop":1744710204330,"duration":1}}]},"0c5df4cfe463ba9921be6be0de586fba":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e7f4ea5c0d204da9","reportUrl":"https://Ajay263.github.io/2024-gitops-minicamp/22//#testresult/e7f4ea5c0d204da9","status":"broken","statusDetails":"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag\n[SQL: SELECT dag.dag_display_name, dag.dag_id, dag.root_dag_id, dag.is_paused, dag.is_subdag, dag.is_active, dag.last_parsed_time, dag.last_pickled, dag.last_expired, dag.scheduler_lock, dag.pickle_id, dag.fileloc, dag.processor_subdir, dag.owners, dag.description, dag.default_view, dag.schedule_interval, dag.timetable_description, dag.dataset_expression, dag.max_active_tasks, dag.max_active_runs, dag.max_consecutive_failed_dag_runs, dag.has_task_concurrency_limits, dag.has_import_errors, dag.next_dagrun, dag.next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end, dag.next_dagrun_create_after \nFROM dag \nWHERE dag.dag_id = ?]\n[parameters: ('dbt_docs_generator',)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","time":{"start":1744710205063,"stop":1744710205063,"duration":0}}]}}